/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FlyoutDropdown: typeof import('./src/components/layout/FlyoutDropdown.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    LangSelect: typeof import('./src/components/layout/LangSelect.vue')['default']
    LogoWithText: typeof import('./src/components/layout/LogoWithText.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Typography: typeof import('./src/components/typography/Typography.vue')['default']
  }
}
